# lastest Docker Compose version
version: "3.9"

# Services declaration
services:

  # Uses redis for storing user's data
  db:
    hostname: redis
    labels:
      - "Database"
      - "REDIS"
    ports:
      - 6379:6379
    image: redis:6.2.1-alpine
    volumes:
      - "redis-data:/data:rw"
    networks:
      - service-network
      
  app:
    build: 
      context: backend
      dockerfile: Dockerfile
      args:
        JAR_FILE: build/libs/backend-0.0.1-SNAPSHOT.jar
    labels:
      - "Service"
      - "Backend"
    ports:
     - "8080:8080"
    links:
      - "db:redis"
    networks:
      - service-network

volumes:
  redis-data:

networks:
  service-network:
    driver: bridge
    
