# lastest Docker Compose version
version: "3.9"

# Services declaration
services:

  # Uses redis for storing user's data
  db:
    hostname: redis
    labels:
      - "Database"
      - "REDIS"
    expose:
      - 6379
    image: redis:6.2.1-alpine
    volumes:
      - "redis-data:/data:rw"
    networks:
      - service-network
      
  app:
    build: 
      context: backend
      dockerfile: Dockerfile
      args:
        JAR_FILE: build/libs/backend-0.0.1-SNAPSHOT.jar
    labels:
      - "Service"
      - "Backend"
    ports:
     - "8080:8080"
    links:
      - "db:redis"
    networks:
      - service-network
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 5

volumes:
  redis-data:

networks:
  service-network:
    driver: bridge
    
