apiVersion: v1
kind: Service
metadata:
  name: password-api
spec:
  selector:
    app: password-api
  ports:
    # El puerto expuesto por el servicio
  - port: 3000
    # El puerto de destino, al que hará de proxy el servicio 
    targetPort: 3000
    protocol: TCP
  type: NodePort
